version: '3.8'
services:
  inatrace-fe:
    image: ${IMAGE_NAME:-ghcr.io/atijaguar-ec/fe-frontend}:${TAG:-latest}
    container_name: inatrace-fe
    ports:
      - "${HTTP_PORT:-80}:80"
    networks:
      - backend
    restart: always
networks:
  backend:
    external: true
    name: inatrace-backend-network
