export const environment = {
  production: false,
  environmentName: 'DEV',
  basePath: '',
  appBaseUrl: 'http://localhost:4200',
  qrCodeBasePath: 'q-cd',
  chainRelativeFileUploadUrl: '',
  chainRelativeFileDownloadUrl: '',
  relativeFileUploadUrl: '/api/common/document',
  relativeFileUploadUrlManualType: '/api/common/document',
  relativeImageUploadUrl: '/api/common/image',
  relativeImageUploadUrlAllSizes: '/api/common/image',
  version: '2.41.0-SNAPSHOT',

  googleMapsApiKey: '',
  googleAnalyticsId: '',
  mapboxAccessToken: '',
  facebookPixelId: null,
  intercomAppId: null,
  chatApp: null,
  rocketChatServer: null,
  tokenForPublicLogRoute: '',
  appName: 'INATrace',
  reloadDelay: 500,
  harcodedLabelForPrivacyOnRegisterPage: '',
  beycoAuthURL: '',
  beycoClientId: '',
};
