/*
 * Copyright(c) 2009 - 2019 Abelium d.o.o.
 * Kajuhova 90, 1000 Ljubljana, Slovenia
 * All rights reserved
 * Copyright(c) 1995 - 2018 T-Systems Multimedia Solutions GmbH
 * Riesaer Str. 5, 01129 Dresden
 * All rights reserved.
 *
 * INATrace Services API
 * INATrace Services API OpenAPI documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the openapi-typescript-angular-generator.
 * https://github.com/alenabelium/openapi-typescript-angular-generator
 * Do not edit the class manually.
 */




/**
 * Companies in the scope of the import
 */

export interface ApiPlotGeoJsonImportCompany { 
    /**
     * Company ID
     */
    id?: number;
    /**
     * Company name
     */
    name?: string;
    /**
     * Plots the company has before the import
     */
    existingPlots?: number;
    /**
     * Whether the existing plots are deleted by the import
     */
    replaced?: boolean;
    /**
     * Plots the import creates for farmers of this company
     */
    newPlots?: number;
}

/**
 * Namespace for property- and property-value-enumerations of ApiPlotGeoJsonImportCompany.
 */
export namespace ApiPlotGeoJsonImportCompany {
    /**
     * All properties of ApiPlotGeoJsonImportCompany.
     */
    export enum Properties {
        /**
         * Company ID
         */
        id = 'id',
        /**
         * Company name
         */
        name = 'name',
        /**
         * Plots the company has before the import
         */
        existingPlots = 'existingPlots',
        /**
         * Whether the existing plots are deleted by the import
         */
        replaced = 'replaced',
        /**
         * Plots the import creates for farmers of this company
         */
        newPlots = 'newPlots'
    }


    export function formMetadata() {
        return  {
            metadata: formMetadata,
            classname: 'ApiPlotGeoJsonImportCompany',
            vars: [
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'id',
                    classname: 'ApiPlotGeoJsonImportCompany',
                    dataType: 'number',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'name',
                    classname: 'ApiPlotGeoJsonImportCompany',
                    dataType: 'string',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'existingPlots',
                    classname: 'ApiPlotGeoJsonImportCompany',
                    dataType: 'number',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'replaced',
                    classname: 'ApiPlotGeoJsonImportCompany',
                    dataType: 'boolean',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'newPlots',
                    classname: 'ApiPlotGeoJsonImportCompany',
                    dataType: 'number',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
            ],
            validators: {
                id: [
                ],
                name: [
                ],
                existingPlots: [
                ],
                replaced: [
                ],
                newPlots: [
                ],
            }
        }
    }

  // export const ApiPlotGeoJsonImportCompanyValidationScheme = {
  //     validators: [],
  //     fields: {
  //               id: {
  //                   validators: []
  //               },
  //               name: {
  //                   validators: []
  //               },
  //               existingPlots: {
  //                   validators: []
  //               },
  //               replaced: {
  //                   validators: []
  //               },
  //               newPlots: {
  //                   validators: []
  //               },
  //     }
  // } as SimpleValidationScheme<ApiPlotGeoJsonImportCompany>;


}


