/*
 * Copyright(c) 2009 - 2019 Abelium d.o.o.
 * Kajuhova 90, 1000 Ljubljana, Slovenia
 * All rights reserved
 * Copyright(c) 1995 - 2018 T-Systems Multimedia Solutions GmbH
 * Riesaer Str. 5, 01129 Dresden
 * All rights reserved.
 *
 * INATrace Services API
 * INATrace Services API OpenAPI documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the openapi-typescript-angular-generator.
 * https://github.com/alenabelium/openapi-typescript-angular-generator
 * Do not edit the class manually.
 */




/**
 * Translations for the defect
 */

export interface ApiShrimpFlavorDefectTranslation { 
    /**
     * Language of the translation
     */
    language?: ApiShrimpFlavorDefectTranslation.LanguageEnum;
    /**
     * Translated name
     */
    name?: string;
    /**
     * Translated description
     */
    description?: string;
}

/**
 * Namespace for property- and property-value-enumerations of ApiShrimpFlavorDefectTranslation.
 */
export namespace ApiShrimpFlavorDefectTranslation {
    /**
     * All properties of ApiShrimpFlavorDefectTranslation.
     */
    export enum Properties {
        /**
         * Language of the translation
         */
        language = 'language',
        /**
         * Translated name
         */
        name = 'name',
        /**
         * Translated description
         */
        description = 'description'
    }

    /**
     * All possible values of language.
     */
    export enum LanguageEnum {
        EN = 'EN',
        DE = 'DE',
        RW = 'RW',
        ES = 'ES'
    }


    export function formMetadata() {
        return  {
            metadata: formMetadata,
            classname: 'ApiShrimpFlavorDefectTranslation',
            vars: [
                {
                    isReadOnly: false,
                    isEnum: true,
                    datatypeWithEnum: 'ApiShrimpFlavorDefectTranslation.LanguageEnum',
                    required: false,
                    name: 'language',
                    classname: 'ApiShrimpFlavorDefectTranslation',
                    dataType: 'string',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'name',
                    classname: 'ApiShrimpFlavorDefectTranslation',
                    dataType: 'string',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'description',
                    classname: 'ApiShrimpFlavorDefectTranslation',
                    dataType: 'string',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
            ],
            validators: {
                language: [
                ],
                name: [
                ],
                description: [
                ],
            }
        }
    }

  // export const ApiShrimpFlavorDefectTranslationValidationScheme = {
  //     validators: [],
  //     fields: {
  //               language: {
  //                   validators: []
  //               },
  //               name: {
  //                   validators: []
  //               },
  //               description: {
  //                   validators: []
  //               },
  //     }
  // } as SimpleValidationScheme<ApiShrimpFlavorDefectTranslation>;


}


