/*
 * Copyright(c) 2009 - 2019 Abelium d.o.o.
 * Kajuhova 90, 1000 Ljubljana, Slovenia
 * All rights reserved
 * Copyright(c) 1995 - 2018 T-Systems Multimedia Solutions GmbH
 * Riesaer Str. 5, 01129 Dresden
 * All rights reserved.
 *
 * INATrace Services API
 * INATrace Services API OpenAPI documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the openapi-typescript-angular-generator.
 * https://github.com/alenabelium/openapi-typescript-angular-generator
 * Do not edit the class manually.
 */




/**
 * Translations
 */

export interface ApiShrimpTreatmentTypeTranslation { 
    /**
     * Language code
     */
    language?: ApiShrimpTreatmentTypeTranslation.LanguageEnum;
    /**
     * Translated label
     */
    label?: string;
    /**
     * Translated description
     */
    description?: string;
}

/**
 * Namespace for property- and property-value-enumerations of ApiShrimpTreatmentTypeTranslation.
 */
export namespace ApiShrimpTreatmentTypeTranslation {
    /**
     * All properties of ApiShrimpTreatmentTypeTranslation.
     */
    export enum Properties {
        /**
         * Language code
         */
        language = 'language',
        /**
         * Translated label
         */
        label = 'label',
        /**
         * Translated description
         */
        description = 'description'
    }

    /**
     * All possible values of language.
     */
    export enum LanguageEnum {
        EN = 'EN',
        DE = 'DE',
        RW = 'RW',
        ES = 'ES'
    }


    export function formMetadata() {
        return  {
            metadata: formMetadata,
            classname: 'ApiShrimpTreatmentTypeTranslation',
            vars: [
                {
                    isReadOnly: false,
                    isEnum: true,
                    datatypeWithEnum: 'ApiShrimpTreatmentTypeTranslation.LanguageEnum',
                    required: false,
                    name: 'language',
                    classname: 'ApiShrimpTreatmentTypeTranslation',
                    dataType: 'string',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'label',
                    classname: 'ApiShrimpTreatmentTypeTranslation',
                    dataType: 'string',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'description',
                    classname: 'ApiShrimpTreatmentTypeTranslation',
                    dataType: 'string',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
            ],
            validators: {
                language: [
                ],
                label: [
                ],
                description: [
                ],
            }
        }
    }

  // export const ApiShrimpTreatmentTypeTranslationValidationScheme = {
  //     validators: [],
  //     fields: {
  //               language: {
  //                   validators: []
  //               },
  //               label: {
  //                   validators: []
  //               },
  //               description: {
  //                   validators: []
  //               },
  //     }
  // } as SimpleValidationScheme<ApiShrimpTreatmentTypeTranslation>;


}


