version: "3.8"

services:
  # Reverse proxy that terminates TLS and routes to FE
  nginx-proxy:
    image: nginxproxy/nginx-proxy:alpine
    container_name: inatrace-nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - frontend
    restart: always

  # ACME companion issues/renews Let's Encrypt certs automatically
  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    container_name: inatrace-nginx-proxy-acme
    depends_on:
      - nginx-proxy
    environment:
      - DEFAULT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - frontend
    restart: always

  # Frontend container (unchanged image). TLS handled by nginx-proxy above.
  inatrace-frontend:
    image: ${IMAGE_NAME}:${TAG}
    container_name: inatrace-fe
    environment:
      - VIRTUAL_HOST=${FRONTEND_DOMAIN}
      - LETSENCRYPT_HOST=${FRONTEND_DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - HTTPS_METHOD=redirect
      - VIRTUAL_PORT=80
    expose:
      - "80"
    networks:
      - frontend
      - backend
    restart: always

networks:
  frontend:
    name: inatrace-frontend-network
  backend:
    external: true
    name: inatrace-backend-network

volumes:
  certs:
  vhost:
  html:
