
services:

  inatrace-frontend:
    image: ${IMAGE_NAME}:${TAG}
    container_name: inatrace-fe
    networks:
      - frontend
      - backend
    ports:
      - "8081:80"
    restart: always

networks:
  frontend:
    name: inatrace-frontend-network
  backend:
    external: true
    name: inatrace-backend-network
