server {
    listen 80;
    server_name testinatrace.espam.edu.ec;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/letsencrypt;
        default_type "text/plain";
        try_files $uri =404;
    }

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name testinatrace.espam.edu.ec;

    ssl_certificate     /etc/letsencrypt/live/testinatrace.espam.edu.ec/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/testinatrace.espam.edu.ec/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/letsencrypt;
        default_type "text/plain";
        try_files $uri =404;
    }

    # Proxy a Frontend Angular (Docker container)
    location / {
        proxy_pass http://127.0.0.1:8081;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_read_timeout 60s;
        proxy_connect_timeout 5s;
    }

    # Proxy a Backend Java/Spring (Docker container)
    location /api/ {
        proxy_pass http://127.0.0.1:8082/api/;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_read_timeout 60s;
        proxy_connect_timeout 5s;
    }

    # Proxy a Jenkins (Docker container / local process)
    location /jenkins/ {
        proxy_pass http://127.0.0.1:8080/jenkins/;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host  $host;
        proxy_set_header X-Forwarded-Port  $server_port;
        proxy_redirect off;
        proxy_http_version 1.1;
        proxy_read_timeout 60s;
        proxy_connect_timeout 5s;
     }
     
    # Proxy a WMS / Geoserver externo
    location /wms {
        proxy_pass http://ide.ambiente.gob.ec:8080/geoserver/mae_ide/wms;
        proxy_set_header Host ide.ambiente.gob.ec;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Accept "image/png,image/*;q=0.8,*/*;q=0.5";
        proxy_http_version 1.1;
        proxy_read_timeout 120s;
        proxy_connect_timeout 30s;
        proxy_send_timeout 30s;
        proxy_buffering off;
        proxy_redirect http://ide.ambiente.gob.ec:8080/geoserver/mae_ide/wms /wms;
     }
}
