/*
 * Copyright(c) 2009 - 2019 Abelium d.o.o.
 * Kajuhova 90, 1000 Ljubljana, Slovenia
 * All rights reserved
 * Copyright(c) 1995 - 2018 T-Systems Multimedia Solutions GmbH
 * Riesaer Str. 5, 01129 Dresden
 * All rights reserved.
 *
 * INATrace Services API
 * INATrace Services API OpenAPI documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the openapi-typescript-angular-generator.
 * https://github.com/alenabelium/openapi-typescript-angular-generator
 * Do not edit the class manually.
 */




/**
 * Field inspection record for shrimp sensorial tests at farms
 */

export interface ApiFieldInspection { 
    /**
     * Entity ID
     */
    id?: number;
    /**
     * Creation timestamp
     */
    creationTimestamp?: Date;
    /**
     * Update timestamp
     */
    updateTimestamp?: Date;
    /**
     * User ID who created this inspection
     */
    createdById?: number;
    /**
     * User ID who last updated this inspection
     */
    updatedById?: number;
    /**
     * Source stock order ID (order at field inspection facility)
     */
    sourceStockOrderId?: number;
    /**
     * Source stock order identifier
     */
    sourceStockOrderIdentifier?: string;
    /**
     * Destination stock order ID (order at packing plant, null if available)
     */
    destinationStockOrderId?: number;
    /**
     * Company ID that owns this inspection
     */
    companyId?: number;
    /**
     * Date when the inspection was performed
     */
    inspectionDate?: Date;
    /**
     * Time of inspection in HH:mm format
     */
    inspectionTime?: string;
    /**
     * Producer/supplier ID
     */
    producerUserCustomerId?: number;
    /**
     * Producer name for display
     */
    producerName?: string;
    /**
     * Flavor test result: NORMAL or DEFECT
     */
    flavorTestResult?: string;
    /**
     * Flavor defect type ID (if result is DEFECT)
     */
    flavorDefectTypeId?: number;
    /**
     * Flavor defect type code
     */
    flavorDefectTypeCode?: string;
    /**
     * Flavor defect type label
     */
    flavorDefectTypeLabel?: string;
    /**
     * Whether purchase is recommended
     */
    purchaseRecommended?: boolean;
    /**
     * Additional inspection notes
     */
    inspectionNotes?: string;
    /**
     * Number of gavetas (crates)
     */
    numberOfGavetas?: number;
    /**
     * Number of bines (bins)
     */
    numberOfBines?: number;
    /**
     * Number of piscinas (ponds)
     */
    numberOfPiscinas?: number;
    /**
     * Guía de remisión number
     */
    guiaRemisionNumber?: string;
    /**
     * Total quantity in units
     */
    totalQuantity?: number;
    /**
     * Whether this inspection is available for linking
     */
    available?: boolean;
}

/**
 * Namespace for property- and property-value-enumerations of ApiFieldInspection.
 */
export namespace ApiFieldInspection {
    /**
     * All properties of ApiFieldInspection.
     */
    export enum Properties {
        /**
         * Entity ID
         */
        id = 'id',
        /**
         * Creation timestamp
         */
        creationTimestamp = 'creationTimestamp',
        /**
         * Update timestamp
         */
        updateTimestamp = 'updateTimestamp',
        /**
         * User ID who created this inspection
         */
        createdById = 'createdById',
        /**
         * User ID who last updated this inspection
         */
        updatedById = 'updatedById',
        /**
         * Source stock order ID (order at field inspection facility)
         */
        sourceStockOrderId = 'sourceStockOrderId',
        /**
         * Source stock order identifier
         */
        sourceStockOrderIdentifier = 'sourceStockOrderIdentifier',
        /**
         * Destination stock order ID (order at packing plant, null if available)
         */
        destinationStockOrderId = 'destinationStockOrderId',
        /**
         * Company ID that owns this inspection
         */
        companyId = 'companyId',
        /**
         * Date when the inspection was performed
         */
        inspectionDate = 'inspectionDate',
        /**
         * Time of inspection in HH:mm format
         */
        inspectionTime = 'inspectionTime',
        /**
         * Producer/supplier ID
         */
        producerUserCustomerId = 'producerUserCustomerId',
        /**
         * Producer name for display
         */
        producerName = 'producerName',
        /**
         * Flavor test result: NORMAL or DEFECT
         */
        flavorTestResult = 'flavorTestResult',
        /**
         * Flavor defect type ID (if result is DEFECT)
         */
        flavorDefectTypeId = 'flavorDefectTypeId',
        /**
         * Flavor defect type code
         */
        flavorDefectTypeCode = 'flavorDefectTypeCode',
        /**
         * Flavor defect type label
         */
        flavorDefectTypeLabel = 'flavorDefectTypeLabel',
        /**
         * Whether purchase is recommended
         */
        purchaseRecommended = 'purchaseRecommended',
        /**
         * Additional inspection notes
         */
        inspectionNotes = 'inspectionNotes',
        /**
         * Number of gavetas (crates)
         */
        numberOfGavetas = 'numberOfGavetas',
        /**
         * Number of bines (bins)
         */
        numberOfBines = 'numberOfBines',
        /**
         * Number of piscinas (ponds)
         */
        numberOfPiscinas = 'numberOfPiscinas',
        /**
         * Guía de remisión number
         */
        guiaRemisionNumber = 'guiaRemisionNumber',
        /**
         * Total quantity in units
         */
        totalQuantity = 'totalQuantity',
        /**
         * Whether this inspection is available for linking
         */
        available = 'available'
    }


    export function formMetadata() {
        return  {
            metadata: formMetadata,
            classname: 'ApiFieldInspection',
            vars: [
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'id',
                    classname: 'ApiFieldInspection',
                    dataType: 'number',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'creationTimestamp',
                    classname: 'ApiFieldInspection',
                    dataType: 'Date',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'updateTimestamp',
                    classname: 'ApiFieldInspection',
                    dataType: 'Date',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'createdById',
                    classname: 'ApiFieldInspection',
                    dataType: 'number',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'updatedById',
                    classname: 'ApiFieldInspection',
                    dataType: 'number',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'sourceStockOrderId',
                    classname: 'ApiFieldInspection',
                    dataType: 'number',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'sourceStockOrderIdentifier',
                    classname: 'ApiFieldInspection',
                    dataType: 'string',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'destinationStockOrderId',
                    classname: 'ApiFieldInspection',
                    dataType: 'number',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'companyId',
                    classname: 'ApiFieldInspection',
                    dataType: 'number',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'inspectionDate',
                    classname: 'ApiFieldInspection',
                    dataType: 'Date',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'inspectionTime',
                    classname: 'ApiFieldInspection',
                    dataType: 'string',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'producerUserCustomerId',
                    classname: 'ApiFieldInspection',
                    dataType: 'number',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'producerName',
                    classname: 'ApiFieldInspection',
                    dataType: 'string',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'flavorTestResult',
                    classname: 'ApiFieldInspection',
                    dataType: 'string',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'flavorDefectTypeId',
                    classname: 'ApiFieldInspection',
                    dataType: 'number',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'flavorDefectTypeCode',
                    classname: 'ApiFieldInspection',
                    dataType: 'string',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'flavorDefectTypeLabel',
                    classname: 'ApiFieldInspection',
                    dataType: 'string',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'purchaseRecommended',
                    classname: 'ApiFieldInspection',
                    dataType: 'boolean',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'inspectionNotes',
                    classname: 'ApiFieldInspection',
                    dataType: 'string',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'numberOfGavetas',
                    classname: 'ApiFieldInspection',
                    dataType: 'number',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'numberOfBines',
                    classname: 'ApiFieldInspection',
                    dataType: 'number',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'numberOfPiscinas',
                    classname: 'ApiFieldInspection',
                    dataType: 'number',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'guiaRemisionNumber',
                    classname: 'ApiFieldInspection',
                    dataType: 'string',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'totalQuantity',
                    classname: 'ApiFieldInspection',
                    dataType: 'number',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'available',
                    classname: 'ApiFieldInspection',
                    dataType: 'boolean',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
            ],
            validators: {
                id: [
                ],
                creationTimestamp: [
                ],
                updateTimestamp: [
                ],
                createdById: [
                ],
                updatedById: [
                ],
                sourceStockOrderId: [
                ],
                sourceStockOrderIdentifier: [
                ],
                destinationStockOrderId: [
                ],
                companyId: [
                ],
                inspectionDate: [
                ],
                inspectionTime: [
                ],
                producerUserCustomerId: [
                ],
                producerName: [
                ],
                flavorTestResult: [
                ],
                flavorDefectTypeId: [
                ],
                flavorDefectTypeCode: [
                ],
                flavorDefectTypeLabel: [
                ],
                purchaseRecommended: [
                ],
                inspectionNotes: [
                ],
                numberOfGavetas: [
                ],
                numberOfBines: [
                ],
                numberOfPiscinas: [
                ],
                guiaRemisionNumber: [
                ],
                totalQuantity: [
                ],
                available: [
                ],
            }
        }
    }

  // export const ApiFieldInspectionValidationScheme = {
  //     validators: [],
  //     fields: {
  //               id: {
  //                   validators: []
  //               },
  //               creationTimestamp: {
  //                   validators: []
  //               },
  //               updateTimestamp: {
  //                   validators: []
  //               },
  //               createdById: {
  //                   validators: []
  //               },
  //               updatedById: {
  //                   validators: []
  //               },
  //               sourceStockOrderId: {
  //                   validators: []
  //               },
  //               sourceStockOrderIdentifier: {
  //                   validators: []
  //               },
  //               destinationStockOrderId: {
  //                   validators: []
  //               },
  //               companyId: {
  //                   validators: []
  //               },
  //               inspectionDate: {
  //                   validators: []
  //               },
  //               inspectionTime: {
  //                   validators: []
  //               },
  //               producerUserCustomerId: {
  //                   validators: []
  //               },
  //               producerName: {
  //                   validators: []
  //               },
  //               flavorTestResult: {
  //                   validators: []
  //               },
  //               flavorDefectTypeId: {
  //                   validators: []
  //               },
  //               flavorDefectTypeCode: {
  //                   validators: []
  //               },
  //               flavorDefectTypeLabel: {
  //                   validators: []
  //               },
  //               purchaseRecommended: {
  //                   validators: []
  //               },
  //               inspectionNotes: {
  //                   validators: []
  //               },
  //               numberOfGavetas: {
  //                   validators: []
  //               },
  //               numberOfBines: {
  //                   validators: []
  //               },
  //               numberOfPiscinas: {
  //                   validators: []
  //               },
  //               guiaRemisionNumber: {
  //                   validators: []
  //               },
  //               totalQuantity: {
  //                   validators: []
  //               },
  //               available: {
  //                   validators: []
  //               },
  //     }
  // } as SimpleValidationScheme<ApiFieldInspection>;


}


