/*
 * Copyright(c) 2009 - 2019 Abelium d.o.o.
 * Kajuhova 90, 1000 Ljubljana, Slovenia
 * All rights reserved
 * Copyright(c) 1995 - 2018 T-Systems Multimedia Solutions GmbH
 * Riesaer Str. 5, 01129 Dresden
 * All rights reserved.
 *
 * INATrace Services API
 * INATrace Services API OpenAPI documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the openapi-typescript-angular-generator.
 * https://github.com/alenabelium/openapi-typescript-angular-generator
 * Do not edit the class manually.
 */


import { ApiShrimpMachineTranslation } from './apiShrimpMachineTranslation';



export interface ApiShrimpMachine { 
    /**
     * Entity id
     */
    id?: number;
    /**
     * Unique code (MACH_01, GLAZER_01, etc.)
     */
    code?: string;
    /**
     * Machine name/label
     */
    label?: string;
    /**
     * Description
     */
    description?: string;
    /**
     * Machine type (CLASSIFIER, FREEZER, GLAZER, PACKER)
     */
    machineType?: string;
    /**
     * Display order
     */
    displayOrder?: number;
    /**
     * Status
     */
    status?: ApiShrimpMachine.StatusEnum;
    /**
     * Translations
     */
    translations?: Array<ApiShrimpMachineTranslation>;
}

/**
 * Namespace for property- and property-value-enumerations of ApiShrimpMachine.
 */
export namespace ApiShrimpMachine {
    /**
     * All properties of ApiShrimpMachine.
     */
    export enum Properties {
        /**
         * Entity id
         */
        id = 'id',
        /**
         * Unique code (MACH_01, GLAZER_01, etc.)
         */
        code = 'code',
        /**
         * Machine name/label
         */
        label = 'label',
        /**
         * Description
         */
        description = 'description',
        /**
         * Machine type (CLASSIFIER, FREEZER, GLAZER, PACKER)
         */
        machineType = 'machineType',
        /**
         * Display order
         */
        displayOrder = 'displayOrder',
        /**
         * Status
         */
        status = 'status',
        /**
         * Translations
         */
        translations = 'translations'
    }

    /**
     * All possible values of status.
     */
    export enum StatusEnum {
        ACTIVE = 'ACTIVE',
        INACTIVE = 'INACTIVE'
    }


    export function formMetadata() {
        return  {
            metadata: formMetadata,
            classname: 'ApiShrimpMachine',
            vars: [
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'id',
                    classname: 'ApiShrimpMachine',
                    dataType: 'number',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'code',
                    classname: 'ApiShrimpMachine',
                    dataType: 'string',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'label',
                    classname: 'ApiShrimpMachine',
                    dataType: 'string',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'description',
                    classname: 'ApiShrimpMachine',
                    dataType: 'string',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'machineType',
                    classname: 'ApiShrimpMachine',
                    dataType: 'string',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'displayOrder',
                    classname: 'ApiShrimpMachine',
                    dataType: 'number',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: true,
                    datatypeWithEnum: 'ApiShrimpMachine.StatusEnum',
                    required: false,
                    name: 'status',
                    classname: 'ApiShrimpMachine',
                    dataType: 'string',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    metadata: ApiShrimpMachineTranslation.formMetadata,
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'translations',
                    classname: 'ApiShrimpMachine',
                    dataType: 'Array&lt;ApiShrimpMachineTranslation&gt;',
                    isPrimitiveType: false,
                    isListContainer: true,
                    complexType: 'ApiShrimpMachineTranslation'
                },
            ],
            validators: {
                id: [
                ],
                code: [
                ],
                label: [
                ],
                description: [
                ],
                machineType: [
                ],
                displayOrder: [
                ],
                status: [
                ],
                translations: [
                ],
            }
        }
    }

  // export const ApiShrimpMachineValidationScheme = {
  //     validators: [],
  //     fields: {
  //               id: {
  //                   validators: []
  //               },
  //               code: {
  //                   validators: []
  //               },
  //               label: {
  //                   validators: []
  //               },
  //               description: {
  //                   validators: []
  //               },
  //               machineType: {
  //                   validators: []
  //               },
  //               displayOrder: {
  //                   validators: []
  //               },
  //               status: {
  //                   validators: []
  //               },
  //               translations: {
  //                   validators: []
  //               },
  //     }
  // } as SimpleValidationScheme<ApiShrimpMachine>;


}


