/*
 * Copyright(c) 2009 - 2019 Abelium d.o.o.
 * Kajuhova 90, 1000 Ljubljana, Slovenia
 * All rights reserved
 * Copyright(c) 1995 - 2018 T-Systems Multimedia Solutions GmbH
 * Riesaer Str. 5, 01129 Dresden
 * All rights reserved.
 *
 * INATrace Services API
 * INATrace Services API OpenAPI documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the openapi-typescript-angular-generator.
 * https://github.com/alenabelium/openapi-typescript-angular-generator
 * Do not edit the class manually.
 */


import { ApiShrimpBrandTranslation } from './apiShrimpBrandTranslation';



export interface ApiShrimpBrand { 
    /**
     * Entity id
     */
    id?: number;
    /**
     * Unique code (DUFER_2KG, DUFER_5LB, etc.)
     */
    code?: string;
    /**
     * Brand name/label
     */
    label?: string;
    /**
     * Description
     */
    description?: string;
    /**
     * Default weight per box for this brand
     */
    weightPerBox?: number;
    /**
     * Measure unit for the weight (KG, LB)
     */
    measureUnit?: string;
    /**
     * Display order
     */
    displayOrder?: number;
    /**
     * Status
     */
    status?: ApiShrimpBrand.StatusEnum;
    /**
     * Translations
     */
    translations?: Array<ApiShrimpBrandTranslation>;
}

/**
 * Namespace for property- and property-value-enumerations of ApiShrimpBrand.
 */
export namespace ApiShrimpBrand {
    /**
     * All properties of ApiShrimpBrand.
     */
    export enum Properties {
        /**
         * Entity id
         */
        id = 'id',
        /**
         * Unique code (DUFER_2KG, DUFER_5LB, etc.)
         */
        code = 'code',
        /**
         * Brand name/label
         */
        label = 'label',
        /**
         * Description
         */
        description = 'description',
        /**
         * Default weight per box for this brand
         */
        weightPerBox = 'weightPerBox',
        /**
         * Measure unit for the weight (KG, LB)
         */
        measureUnit = 'measureUnit',
        /**
         * Display order
         */
        displayOrder = 'displayOrder',
        /**
         * Status
         */
        status = 'status',
        /**
         * Translations
         */
        translations = 'translations'
    }

    /**
     * All possible values of status.
     */
    export enum StatusEnum {
        ACTIVE = 'ACTIVE',
        INACTIVE = 'INACTIVE'
    }


    export function formMetadata() {
        return  {
            metadata: formMetadata,
            classname: 'ApiShrimpBrand',
            vars: [
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'id',
                    classname: 'ApiShrimpBrand',
                    dataType: 'number',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'code',
                    classname: 'ApiShrimpBrand',
                    dataType: 'string',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'label',
                    classname: 'ApiShrimpBrand',
                    dataType: 'string',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'description',
                    classname: 'ApiShrimpBrand',
                    dataType: 'string',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'weightPerBox',
                    classname: 'ApiShrimpBrand',
                    dataType: 'number',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'measureUnit',
                    classname: 'ApiShrimpBrand',
                    dataType: 'string',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'displayOrder',
                    classname: 'ApiShrimpBrand',
                    dataType: 'number',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: true,
                    datatypeWithEnum: 'ApiShrimpBrand.StatusEnum',
                    required: false,
                    name: 'status',
                    classname: 'ApiShrimpBrand',
                    dataType: 'string',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    metadata: ApiShrimpBrandTranslation.formMetadata,
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'translations',
                    classname: 'ApiShrimpBrand',
                    dataType: 'Array&lt;ApiShrimpBrandTranslation&gt;',
                    isPrimitiveType: false,
                    isListContainer: true,
                    complexType: 'ApiShrimpBrandTranslation'
                },
            ],
            validators: {
                id: [
                ],
                code: [
                ],
                label: [
                ],
                description: [
                ],
                weightPerBox: [
                ],
                measureUnit: [
                ],
                displayOrder: [
                ],
                status: [
                ],
                translations: [
                ],
            }
        }
    }

  // export const ApiShrimpBrandValidationScheme = {
  //     validators: [],
  //     fields: {
  //               id: {
  //                   validators: []
  //               },
  //               code: {
  //                   validators: []
  //               },
  //               label: {
  //                   validators: []
  //               },
  //               description: {
  //                   validators: []
  //               },
  //               weightPerBox: {
  //                   validators: []
  //               },
  //               measureUnit: {
  //                   validators: []
  //               },
  //               displayOrder: {
  //                   validators: []
  //               },
  //               status: {
  //                   validators: []
  //               },
  //               translations: {
  //                   validators: []
  //               },
  //     }
  // } as SimpleValidationScheme<ApiShrimpBrand>;


}


