/*
 * Copyright(c) 2009 - 2019 Abelium d.o.o.
 * Kajuhova 90, 1000 Ljubljana, Slovenia
 * All rights reserved
 * Copyright(c) 1995 - 2018 T-Systems Multimedia Solutions GmbH
 * Riesaer Str. 5, 01129 Dresden
 * All rights reserved.
 *
 * INATrace Services API
 * INATrace Services API OpenAPI documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the openapi-typescript-angular-generator.
 * https://github.com/alenabelium/openapi-typescript-angular-generator
 * Do not edit the class manually.
 */


import { ApiShrimpFlavorDefectTranslation } from './apiShrimpFlavorDefectTranslation';



export interface ApiShrimpFlavorDefect { 
    /**
     * Entity id
     */
    id?: number;
    /**
     * code
     */
    code: string;
    /**
     * label
     */
    label: string;
    /**
     * Description of the defect
     */
    description?: string;
    /**
     * Display order in lists
     */
    displayOrder?: number;
    /**
     * Status of the defect (ACTIVE or INACTIVE)
     */
    status?: ApiShrimpFlavorDefect.StatusEnum;
    /**
     * Translations for the defect
     */
    translations?: Array<ApiShrimpFlavorDefectTranslation>;
}

/**
 * Namespace for property- and property-value-enumerations of ApiShrimpFlavorDefect.
 */
export namespace ApiShrimpFlavorDefect {
    /**
     * All properties of ApiShrimpFlavorDefect.
     */
    export enum Properties {
        /**
         * Entity id
         */
        id = 'id',
        /**
         * code
         */
        code = 'code',
        /**
         * label
         */
        label = 'label',
        /**
         * Description of the defect
         */
        description = 'description',
        /**
         * Display order in lists
         */
        displayOrder = 'displayOrder',
        /**
         * Status of the defect (ACTIVE or INACTIVE)
         */
        status = 'status',
        /**
         * Translations for the defect
         */
        translations = 'translations'
    }

    /**
     * All possible values of status.
     */
    export enum StatusEnum {
        ACTIVE = 'ACTIVE',
        INACTIVE = 'INACTIVE'
    }


    export function formMetadata() {
        return  {
            metadata: formMetadata,
            classname: 'ApiShrimpFlavorDefect',
            vars: [
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'id',
                    classname: 'ApiShrimpFlavorDefect',
                    dataType: 'number',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: true,
                    name: 'code',
                    classname: 'ApiShrimpFlavorDefect',
                    dataType: 'string',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: true,
                    name: 'label',
                    classname: 'ApiShrimpFlavorDefect',
                    dataType: 'string',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'description',
                    classname: 'ApiShrimpFlavorDefect',
                    dataType: 'string',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'displayOrder',
                    classname: 'ApiShrimpFlavorDefect',
                    dataType: 'number',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    isReadOnly: false,
                    isEnum: true,
                    datatypeWithEnum: 'ApiShrimpFlavorDefect.StatusEnum',
                    required: false,
                    name: 'status',
                    classname: 'ApiShrimpFlavorDefect',
                    dataType: 'string',
                    isPrimitiveType: true,
                    isListContainer: false,
                    complexType: ''
                },
                {
                    metadata: ApiShrimpFlavorDefectTranslation.formMetadata,
                    isReadOnly: false,
                    isEnum: false,
                    required: false,
                    name: 'translations',
                    classname: 'ApiShrimpFlavorDefect',
                    dataType: 'Array&lt;ApiShrimpFlavorDefectTranslation&gt;',
                    isPrimitiveType: false,
                    isListContainer: true,
                    complexType: 'ApiShrimpFlavorDefectTranslation'
                },
            ],
            validators: {
                id: [
                ],
                code: [
                        ['required'],
                ],
                label: [
                        ['required'],
                ],
                description: [
                ],
                displayOrder: [
                ],
                status: [
                ],
                translations: [
                ],
            }
        }
    }

  // export const ApiShrimpFlavorDefectValidationScheme = {
  //     validators: [],
  //     fields: {
  //               id: {
  //                   validators: []
  //               },
  //               code: {
  //                   validators: []
  //               },
  //               label: {
  //                   validators: []
  //               },
  //               description: {
  //                   validators: []
  //               },
  //               displayOrder: {
  //                   validators: []
  //               },
  //               status: {
  //                   validators: []
  //               },
  //               translations: {
  //                   validators: []
  //               },
  //     }
  // } as SimpleValidationScheme<ApiShrimpFlavorDefect>;


}


