/*
 * Copyright(c) 2009 - 2019 Abelium d.o.o.
 * Kajuhova 90, 1000 Ljubljana, Slovenia
 * All rights reserved
 * Copyright(c) 1995 - 2018 T-Systems Multimedia Solutions GmbH
 * Riesaer Str. 5, 01129 Dresden
 * All rights reserved.
 *
 * INATrace Services API
 * INATrace Services API OpenAPI documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the openapi-typescript-angular-generator.
 * https://github.com/alenabelium/openapi-typescript-angular-generator
 * Do not edit the class manually.
 */

/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { ValidatorFn, Validators } from '@angular/forms';

import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';
import { catchError }                                        from 'rxjs/operators';

import { ApiDefaultResponse } from '../model/apiDefaultResponse';
import { ApiResponseListApiLaboratoryAnalysis } from '../model/apiResponseListApiLaboratoryAnalysis';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';

/**
 * Namespace for getApprovedAvailableForCompany.
 */
export namespace GetApprovedAvailableForCompany {
    /**
     * Parameter map for getApprovedAvailableForCompany.
     */
    export interface PartialParamMap {
      /**
       * Company ID
       */
      companyId: number;
      language?: 'EN' | 'DE' | 'RW' | 'ES';
    }

    /**
     * Enumeration of all parameters for getApprovedAvailableForCompany.
     */
    export enum Parameters {
      /**
       * Company ID
       */
      companyId = 'companyId',
      language = 'language'
    }

    /**
     * A map of tuples with error name and `ValidatorFn` for each parameter of getApprovedAvailableForCompany
     * that does not have an own model.
     */
    export const ParamValidators: {[K in keyof GetApprovedAvailableForCompany.PartialParamMap]?: [string, ValidatorFn][]} = {
      companyId: [
              ['required', Validators.required],
      ],
      language: [
      ],
    };
}

/**
 * Namespace for markAnalysisUsed.
 */
export namespace MarkAnalysisUsed {
    /**
     * Parameter map for markAnalysisUsed.
     */
    export interface PartialParamMap {
      /**
       * Laboratory analysis ID
       */
      id: number;
      /**
       * Destination StockOrder ID
       */
      destinationStockOrderId: number;
    }

    /**
     * Enumeration of all parameters for markAnalysisUsed.
     */
    export enum Parameters {
      /**
       * Laboratory analysis ID
       */
      id = 'id',
      /**
       * Destination StockOrder ID
       */
      destinationStockOrderId = 'destinationStockOrderId'
    }

    /**
     * A map of tuples with error name and `ValidatorFn` for each parameter of markAnalysisUsed
     * that does not have an own model.
     */
    export const ParamValidators: {[K in keyof MarkAnalysisUsed.PartialParamMap]?: [string, ValidatorFn][]} = {
      id: [
              ['required', Validators.required],
      ],
      destinationStockOrderId: [
              ['required', Validators.required],
      ],
    };
}



@Injectable({
  providedIn: 'root'
})
export class LaboratoryAnalysesService {

    protected basePath = 'http://192.168.100.187:8080';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {

        if (configuration) {
            this.configuration = configuration;
            this.configuration.basePath = configuration.basePath != null ? configuration.basePath : (basePath != null ? basePath : this.basePath);
        } else {
            this.configuration.basePath = basePath != null ? basePath : this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }



  /**
   * List approved and unused laboratory analyses for a company by map.
   * 
   * @param map parameters map to set partial amount of parameters easily
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getApprovedAvailableForCompanyByMap(
    map: GetApprovedAvailableForCompany.PartialParamMap,
    observe?: 'body',
    reportProgress?: boolean): Observable<ApiResponseListApiLaboratoryAnalysis>;
  public getApprovedAvailableForCompanyByMap(
    map: GetApprovedAvailableForCompany.PartialParamMap,
    observe?: 'response',
    reportProgress?: boolean): Observable<HttpResponse<ApiResponseListApiLaboratoryAnalysis>>;
  public getApprovedAvailableForCompanyByMap(
    map: GetApprovedAvailableForCompany.PartialParamMap,
    observe?: 'events',
    reportProgress?: boolean): Observable<HttpEvent<ApiResponseListApiLaboratoryAnalysis>>;
  public getApprovedAvailableForCompanyByMap(
    map: GetApprovedAvailableForCompany.PartialParamMap,
    observe: any = 'body',
    reportProgress: boolean = false): Observable<any> {
    return this.getApprovedAvailableForCompany(
      map.companyId,
      map.language,
      observe,
      reportProgress
    );
  }


    /**
     * List approved and unused laboratory analyses for a company
     * 
     * @param companyId Company ID
     * @param language 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getApprovedAvailableForCompany(companyId: number, language?: 'EN' | 'DE' | 'RW' | 'ES', observe?: 'body', reportProgress?: boolean, additionalHeaders?: Array<Array<string>>): Observable<ApiResponseListApiLaboratoryAnalysis>;
    public getApprovedAvailableForCompany(companyId: number, language?: 'EN' | 'DE' | 'RW' | 'ES', observe?: 'response', reportProgress?: boolean, additionalHeaders?: Array<Array<string>>): Observable<HttpResponse<ApiResponseListApiLaboratoryAnalysis>>;
    public getApprovedAvailableForCompany(companyId: number, language?: 'EN' | 'DE' | 'RW' | 'ES', observe?: 'events', reportProgress?: boolean, additionalHeaders?: Array<Array<string>>): Observable<HttpEvent<ApiResponseListApiLaboratoryAnalysis>>;
    public getApprovedAvailableForCompany(companyId: number, language?: 'EN' | 'DE' | 'RW' | 'ES', observe: any = 'body', reportProgress: boolean = false, additionalHeaders?: Array<Array<string>>): Observable<any> {
        if (companyId === null || companyId === undefined) {
            throw new Error('Required parameter companyId was null or undefined when calling getApprovedAvailableForCompany.');
        }

        let headers = this.defaultHeaders;
        if (language !== undefined && language !== null) {
            headers = headers.set('language', String(language));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

            if (additionalHeaders) {
                for(let pair of additionalHeaders) {
                    headers = headers.set(pair[0], pair[1]);
                }
            }

        const handle = this.httpClient.get<ApiResponseListApiLaboratoryAnalysis>(`${this.configuration.basePath}/api/chain/laboratory-analysis/approved-available/company/${encodeURIComponent(String(companyId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
        if(typeof this.configuration.errorHandler === 'function') {
          return handle.pipe(catchError(err => this.configuration.errorHandler(err, 'getApprovedAvailableForCompany')));
        }
        return handle;
    }


  /**
   * Mark laboratory analysis as used by linking it to a destination stock order by map.
   * 
   * @param map parameters map to set partial amount of parameters easily
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public markAnalysisUsedByMap(
    map: MarkAnalysisUsed.PartialParamMap,
    observe?: 'body',
    reportProgress?: boolean): Observable<ApiDefaultResponse>;
  public markAnalysisUsedByMap(
    map: MarkAnalysisUsed.PartialParamMap,
    observe?: 'response',
    reportProgress?: boolean): Observable<HttpResponse<ApiDefaultResponse>>;
  public markAnalysisUsedByMap(
    map: MarkAnalysisUsed.PartialParamMap,
    observe?: 'events',
    reportProgress?: boolean): Observable<HttpEvent<ApiDefaultResponse>>;
  public markAnalysisUsedByMap(
    map: MarkAnalysisUsed.PartialParamMap,
    observe: any = 'body',
    reportProgress: boolean = false): Observable<any> {
    return this.markAnalysisUsed(
      map.id,
      map.destinationStockOrderId,
      observe,
      reportProgress
    );
  }


    /**
     * Mark laboratory analysis as used by linking it to a destination stock order
     * 
     * @param id Laboratory analysis ID
     * @param destinationStockOrderId Destination StockOrder ID
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public markAnalysisUsed(id: number, destinationStockOrderId: number, observe?: 'body', reportProgress?: boolean, additionalHeaders?: Array<Array<string>>): Observable<ApiDefaultResponse>;
    public markAnalysisUsed(id: number, destinationStockOrderId: number, observe?: 'response', reportProgress?: boolean, additionalHeaders?: Array<Array<string>>): Observable<HttpResponse<ApiDefaultResponse>>;
    public markAnalysisUsed(id: number, destinationStockOrderId: number, observe?: 'events', reportProgress?: boolean, additionalHeaders?: Array<Array<string>>): Observable<HttpEvent<ApiDefaultResponse>>;
    public markAnalysisUsed(id: number, destinationStockOrderId: number, observe: any = 'body', reportProgress: boolean = false, additionalHeaders?: Array<Array<string>>): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling markAnalysisUsed.');
        }
        if (destinationStockOrderId === null || destinationStockOrderId === undefined) {
            throw new Error('Required parameter destinationStockOrderId was null or undefined when calling markAnalysisUsed.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (destinationStockOrderId !== undefined && destinationStockOrderId !== null) {
            queryParameters = queryParameters.set('destinationStockOrderId', <any>destinationStockOrderId);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

            if (additionalHeaders) {
                for(let pair of additionalHeaders) {
                    headers = headers.set(pair[0], pair[1]);
                }
            }

        const handle = this.httpClient.post<ApiDefaultResponse>(`${this.configuration.basePath}/api/chain/laboratory-analysis/${encodeURIComponent(String(id))}/mark-used`,
            null,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
        if(typeof this.configuration.errorHandler === 'function') {
          return handle.pipe(catchError(err => this.configuration.errorHandler(err, 'markAnalysisUsed')));
        }
        return handle;
    }

}
