/*
 * Copyright(c) 2009 - 2019 Abelium d.o.o.
 * Kajuhova 90, 1000 Ljubljana, Slovenia
 * All rights reserved
 * Copyright(c) 1995 - 2018 T-Systems Multimedia Solutions GmbH
 * Riesaer Str. 5, 01129 Dresden
 * All rights reserved.
 *
 * INATrace Services API
 * INATrace Services API OpenAPI documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the openapi-typescript-angular-generator.
 * https://github.com/alenabelium/openapi-typescript-angular-generator
 * Do not edit the class manually.
 */

/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { ValidatorFn, Validators } from '@angular/forms';

import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';
import { catchError }                                        from 'rxjs/operators';

import { ApiCertificationType } from '../model/apiCertificationType';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';

/**
 * Namespace for _delete.
 */
export namespace Delete {
    /**
     * Parameter map for _delete.
     */
    export interface PartialParamMap {
      id: number;
    }

    /**
     * Enumeration of all parameters for _delete.
     */
    export enum Parameters {
      id = 'id'
    }

    /**
     * A map of tuples with error name and `ValidatorFn` for each parameter of _delete
     * that does not have an own model.
     */
    export const ParamValidators: {[K in keyof Delete.PartialParamMap]?: [string, ValidatorFn][]} = {
      id: [
              ['required', Validators.required],
      ],
    };
}

/**
 * Namespace for createOrUpdate.
 */
export namespace CreateOrUpdate {
    /**
     * Parameter map for createOrUpdate.
     */
    export interface PartialParamMap {
      ApiCertificationType: ApiCertificationType;
    }

    /**
     * Enumeration of all parameters for createOrUpdate.
     */
    export enum Parameters {
      ApiCertificationType = 'ApiCertificationType'
    }

    /**
     * A map of tuples with error name and `ValidatorFn` for each parameter of createOrUpdate
     * that does not have an own model.
     */
    export const ParamValidators: {[K in keyof CreateOrUpdate.PartialParamMap]?: [string, ValidatorFn][]} = {
    };
}

/**
 * Namespace for getById.
 */
export namespace GetById {
    /**
     * Parameter map for getById.
     */
    export interface PartialParamMap {
      id: number;
      Language: 'EN' | 'DE' | 'RW' | 'ES';
    }

    /**
     * Enumeration of all parameters for getById.
     */
    export enum Parameters {
      id = 'id',
      Language = 'Language'
    }

    /**
     * A map of tuples with error name and `ValidatorFn` for each parameter of getById
     * that does not have an own model.
     */
    export const ParamValidators: {[K in keyof GetById.PartialParamMap]?: [string, ValidatorFn][]} = {
      id: [
              ['required', Validators.required],
      ],
      Language: [
              ['required', Validators.required],
      ],
    };
}

/**
 * Namespace for listActive.
 */
export namespace ListActive {
    /**
     * Parameter map for listActive.
     */
    export interface PartialParamMap {
      Language: 'EN' | 'DE' | 'RW' | 'ES';
    }

    /**
     * Enumeration of all parameters for listActive.
     */
    export enum Parameters {
      Language = 'Language'
    }

    /**
     * A map of tuples with error name and `ValidatorFn` for each parameter of listActive
     * that does not have an own model.
     */
    export const ParamValidators: {[K in keyof ListActive.PartialParamMap]?: [string, ValidatorFn][]} = {
      Language: [
              ['required', Validators.required],
      ],
    };
}



@Injectable({
  providedIn: 'root'
})
export class CodebookCertificationTypeService {

    protected basePath = 'http://localhost:8082';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {

        if (configuration) {
            this.configuration = configuration;
            this.configuration.basePath = configuration.basePath != null ? configuration.basePath : (basePath != null ? basePath : this.basePath);
        } else {
            this.configuration.basePath = basePath != null ? basePath : this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }



  /**
   * Delete certification type by map.
   * 
   * @param map parameters map to set partial amount of parameters easily
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public _deleteByMap(
    map: Delete.PartialParamMap,
    observe?: 'body',
    reportProgress?: boolean): Observable<any>;
  public _deleteByMap(
    map: Delete.PartialParamMap,
    observe?: 'response',
    reportProgress?: boolean): Observable<HttpResponse<any>>;
  public _deleteByMap(
    map: Delete.PartialParamMap,
    observe?: 'events',
    reportProgress?: boolean): Observable<HttpEvent<any>>;
  public _deleteByMap(
    map: Delete.PartialParamMap,
    observe: any = 'body',
    reportProgress: boolean = false): Observable<any> {
    return this._delete(
      map.id,
      observe,
      reportProgress
    );
  }


    /**
     * Delete certification type
     * 
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public _delete(id: number, observe?: 'body', reportProgress?: boolean, additionalHeaders?: Array<Array<string>>): Observable<any>;
    public _delete(id: number, observe?: 'response', reportProgress?: boolean, additionalHeaders?: Array<Array<string>>): Observable<HttpResponse<any>>;
    public _delete(id: number, observe?: 'events', reportProgress?: boolean, additionalHeaders?: Array<Array<string>>): Observable<HttpEvent<any>>;
    public _delete(id: number, observe: any = 'body', reportProgress: boolean = false, additionalHeaders?: Array<Array<string>>): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling _delete.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

            if (additionalHeaders) {
                for(let pair of additionalHeaders) {
                    headers = headers.set(pair[0], pair[1]);
                }
            }

        const handle = this.httpClient.delete<any>(`${this.configuration.basePath}/api/api/codebook/certification-type/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
        if(typeof this.configuration.errorHandler === 'function') {
          return handle.pipe(catchError(err => this.configuration.errorHandler(err, 'delete')));
        }
        return handle;
    }


  /**
   * Create or update certification type by map.
   * 
   * @param map parameters map to set partial amount of parameters easily
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public createOrUpdateByMap(
    map: CreateOrUpdate.PartialParamMap,
    observe?: 'body',
    reportProgress?: boolean): Observable<ApiCertificationType>;
  public createOrUpdateByMap(
    map: CreateOrUpdate.PartialParamMap,
    observe?: 'response',
    reportProgress?: boolean): Observable<HttpResponse<ApiCertificationType>>;
  public createOrUpdateByMap(
    map: CreateOrUpdate.PartialParamMap,
    observe?: 'events',
    reportProgress?: boolean): Observable<HttpEvent<ApiCertificationType>>;
  public createOrUpdateByMap(
    map: CreateOrUpdate.PartialParamMap,
    observe: any = 'body',
    reportProgress: boolean = false): Observable<any> {
    return this.createOrUpdate(
      map.ApiCertificationType,
      observe,
      reportProgress
    );
  }


    /**
     * Create or update certification type
     * 
     * @param ApiCertificationType 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createOrUpdate(ApiCertificationType: ApiCertificationType, observe?: 'body', reportProgress?: boolean, additionalHeaders?: Array<Array<string>>): Observable<ApiCertificationType>;
    public createOrUpdate(ApiCertificationType: ApiCertificationType, observe?: 'response', reportProgress?: boolean, additionalHeaders?: Array<Array<string>>): Observable<HttpResponse<ApiCertificationType>>;
    public createOrUpdate(ApiCertificationType: ApiCertificationType, observe?: 'events', reportProgress?: boolean, additionalHeaders?: Array<Array<string>>): Observable<HttpEvent<ApiCertificationType>>;
    public createOrUpdate(ApiCertificationType: ApiCertificationType, observe: any = 'body', reportProgress: boolean = false, additionalHeaders?: Array<Array<string>>): Observable<any> {
        if (ApiCertificationType === null || ApiCertificationType === undefined) {
            throw new Error('Required parameter ApiCertificationType was null or undefined when calling createOrUpdate.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

            if (additionalHeaders) {
                for(let pair of additionalHeaders) {
                    headers = headers.set(pair[0], pair[1]);
                }
            }

        const handle = this.httpClient.post<ApiCertificationType>(`${this.configuration.basePath}/api/api/codebook/certification-type`,
            ApiCertificationType,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
        if(typeof this.configuration.errorHandler === 'function') {
          return handle.pipe(catchError(err => this.configuration.errorHandler(err, 'createOrUpdate')));
        }
        return handle;
    }


  /**
   * Get certification type by ID by map.
   * 
   * @param map parameters map to set partial amount of parameters easily
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getByIdByMap(
    map: GetById.PartialParamMap,
    observe?: 'body',
    reportProgress?: boolean): Observable<ApiCertificationType>;
  public getByIdByMap(
    map: GetById.PartialParamMap,
    observe?: 'response',
    reportProgress?: boolean): Observable<HttpResponse<ApiCertificationType>>;
  public getByIdByMap(
    map: GetById.PartialParamMap,
    observe?: 'events',
    reportProgress?: boolean): Observable<HttpEvent<ApiCertificationType>>;
  public getByIdByMap(
    map: GetById.PartialParamMap,
    observe: any = 'body',
    reportProgress: boolean = false): Observable<any> {
    return this.getById(
      map.id,
      map.Language,
      observe,
      reportProgress
    );
  }


    /**
     * Get certification type by ID
     * 
     * @param id 
     * @param Language 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getById(id: number, Language: 'EN' | 'DE' | 'RW' | 'ES', observe?: 'body', reportProgress?: boolean, additionalHeaders?: Array<Array<string>>): Observable<ApiCertificationType>;
    public getById(id: number, Language: 'EN' | 'DE' | 'RW' | 'ES', observe?: 'response', reportProgress?: boolean, additionalHeaders?: Array<Array<string>>): Observable<HttpResponse<ApiCertificationType>>;
    public getById(id: number, Language: 'EN' | 'DE' | 'RW' | 'ES', observe?: 'events', reportProgress?: boolean, additionalHeaders?: Array<Array<string>>): Observable<HttpEvent<ApiCertificationType>>;
    public getById(id: number, Language: 'EN' | 'DE' | 'RW' | 'ES', observe: any = 'body', reportProgress: boolean = false, additionalHeaders?: Array<Array<string>>): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling getById.');
        }
        if (Language === null || Language === undefined) {
            throw new Error('Required parameter Language was null or undefined when calling getById.');
        }

        let headers = this.defaultHeaders;
        if (Language !== undefined && Language !== null) {
            headers = headers.set('Language', String(Language));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

            if (additionalHeaders) {
                for(let pair of additionalHeaders) {
                    headers = headers.set(pair[0], pair[1]);
                }
            }

        const handle = this.httpClient.get<ApiCertificationType>(`${this.configuration.basePath}/api/api/codebook/certification-type/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
        if(typeof this.configuration.errorHandler === 'function') {
          return handle.pipe(catchError(err => this.configuration.errorHandler(err, 'getById')));
        }
        return handle;
    }


  /**
   * List active certification types by map.
   * 
   * @param map parameters map to set partial amount of parameters easily
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public listActiveByMap(
    map: ListActive.PartialParamMap,
    observe?: 'body',
    reportProgress?: boolean): Observable<Array<ApiCertificationType>>;
  public listActiveByMap(
    map: ListActive.PartialParamMap,
    observe?: 'response',
    reportProgress?: boolean): Observable<HttpResponse<Array<ApiCertificationType>>>;
  public listActiveByMap(
    map: ListActive.PartialParamMap,
    observe?: 'events',
    reportProgress?: boolean): Observable<HttpEvent<Array<ApiCertificationType>>>;
  public listActiveByMap(
    map: ListActive.PartialParamMap,
    observe: any = 'body',
    reportProgress: boolean = false): Observable<any> {
    return this.listActive(
      map.Language,
      observe,
      reportProgress
    );
  }


    /**
     * List active certification types
     * 
     * @param Language 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public listActive(Language: 'EN' | 'DE' | 'RW' | 'ES', observe?: 'body', reportProgress?: boolean, additionalHeaders?: Array<Array<string>>): Observable<Array<ApiCertificationType>>;
    public listActive(Language: 'EN' | 'DE' | 'RW' | 'ES', observe?: 'response', reportProgress?: boolean, additionalHeaders?: Array<Array<string>>): Observable<HttpResponse<Array<ApiCertificationType>>>;
    public listActive(Language: 'EN' | 'DE' | 'RW' | 'ES', observe?: 'events', reportProgress?: boolean, additionalHeaders?: Array<Array<string>>): Observable<HttpEvent<Array<ApiCertificationType>>>;
    public listActive(Language: 'EN' | 'DE' | 'RW' | 'ES', observe: any = 'body', reportProgress: boolean = false, additionalHeaders?: Array<Array<string>>): Observable<any> {
        if (Language === null || Language === undefined) {
            throw new Error('Required parameter Language was null or undefined when calling listActive.');
        }

        let headers = this.defaultHeaders;
        if (Language !== undefined && Language !== null) {
            headers = headers.set('Language', String(Language));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

            if (additionalHeaders) {
                for(let pair of additionalHeaders) {
                    headers = headers.set(pair[0], pair[1]);
                }
            }

        const handle = this.httpClient.get<Array<ApiCertificationType>>(`${this.configuration.basePath}/api/api/codebook/certification-type`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
        if(typeof this.configuration.errorHandler === 'function') {
          return handle.pipe(catchError(err => this.configuration.errorHandler(err, 'listActive')));
        }
        return handle;
    }

}
