/*
 * Copyright(c) 2009 - 2019 Abelium d.o.o.
 * Kajuhova 90, 1000 Ljubljana, Slovenia
 * All rights reserved
 * Copyright(c) 1995 - 2018 T-Systems Multimedia Solutions GmbH
 * Riesaer Str. 5, 01129 Dresden
 * All rights reserved.
 *
 * INATrace Services API
 * INATrace Services API OpenAPI documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the openapi-typescript-angular-generator.
 * https://github.com/alenabelium/openapi-typescript-angular-generator
 * Do not edit the class manually.
 */

/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { ValidatorFn, Validators } from '@angular/forms';

import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';
import { catchError }                                        from 'rxjs/operators';

import { ApiDefaultResponse } from '../model/apiDefaultResponse';
import { ApiResponseApiFieldInspection } from '../model/apiResponseApiFieldInspection';
import { ApiResponseListApiFieldInspection } from '../model/apiResponseListApiFieldInspection';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';

/**
 * Namespace for getAvailableForCompany.
 */
export namespace GetAvailableForCompany {
    /**
     * Parameter map for getAvailableForCompany.
     */
    export interface PartialParamMap {
      /**
       * Company ID
       */
      companyId: number;
      /**
       * Only return inspections where purchase is recommended
       */
      onlyRecommended?: boolean;
      language?: 'EN' | 'DE' | 'RW' | 'ES';
    }

    /**
     * Enumeration of all parameters for getAvailableForCompany.
     */
    export enum Parameters {
      /**
       * Company ID
       */
      companyId = 'companyId',
      /**
       * Only return inspections where purchase is recommended
       */
      onlyRecommended = 'onlyRecommended',
      language = 'language'
    }

    /**
     * A map of tuples with error name and `ValidatorFn` for each parameter of getAvailableForCompany
     * that does not have an own model.
     */
    export const ParamValidators: {[K in keyof GetAvailableForCompany.PartialParamMap]?: [string, ValidatorFn][]} = {
      companyId: [
              ['required', Validators.required],
      ],
      onlyRecommended: [
      ],
      language: [
      ],
    };
}

/**
 * Namespace for getById.
 */
export namespace GetById {
    /**
     * Parameter map for getById.
     */
    export interface PartialParamMap {
      /**
       * Field inspection ID
       */
      id: number;
    }

    /**
     * Enumeration of all parameters for getById.
     */
    export enum Parameters {
      /**
       * Field inspection ID
       */
      id = 'id'
    }

    /**
     * A map of tuples with error name and `ValidatorFn` for each parameter of getById
     * that does not have an own model.
     */
    export const ParamValidators: {[K in keyof GetById.PartialParamMap]?: [string, ValidatorFn][]} = {
      id: [
              ['required', Validators.required],
      ],
    };
}

/**
 * Namespace for markInspectionUsed.
 */
export namespace MarkInspectionUsed {
    /**
     * Parameter map for markInspectionUsed.
     */
    export interface PartialParamMap {
      /**
       * Field inspection ID
       */
      id: number;
      /**
       * Destination StockOrder ID at packing plant
       */
      destinationStockOrderId: number;
    }

    /**
     * Enumeration of all parameters for markInspectionUsed.
     */
    export enum Parameters {
      /**
       * Field inspection ID
       */
      id = 'id',
      /**
       * Destination StockOrder ID at packing plant
       */
      destinationStockOrderId = 'destinationStockOrderId'
    }

    /**
     * A map of tuples with error name and `ValidatorFn` for each parameter of markInspectionUsed
     * that does not have an own model.
     */
    export const ParamValidators: {[K in keyof MarkInspectionUsed.PartialParamMap]?: [string, ValidatorFn][]} = {
      id: [
              ['required', Validators.required],
      ],
      destinationStockOrderId: [
              ['required', Validators.required],
      ],
    };
}



@Injectable({
  providedIn: 'root'
})
export class FieldInspectionsService {

    protected basePath = 'http://192.168.100.187:8080';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {

        if (configuration) {
            this.configuration = configuration;
            this.configuration.basePath = configuration.basePath != null ? configuration.basePath : (basePath != null ? basePath : this.basePath);
        } else {
            this.configuration.basePath = basePath != null ? basePath : this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }



  /**
   * List available field inspections for a company by map.
   * Returns field inspections that are not yet linked to a packing plant delivery
   * @param map parameters map to set partial amount of parameters easily
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getAvailableForCompanyByMap(
    map: GetAvailableForCompany.PartialParamMap,
    observe?: 'body',
    reportProgress?: boolean): Observable<ApiResponseListApiFieldInspection>;
  public getAvailableForCompanyByMap(
    map: GetAvailableForCompany.PartialParamMap,
    observe?: 'response',
    reportProgress?: boolean): Observable<HttpResponse<ApiResponseListApiFieldInspection>>;
  public getAvailableForCompanyByMap(
    map: GetAvailableForCompany.PartialParamMap,
    observe?: 'events',
    reportProgress?: boolean): Observable<HttpEvent<ApiResponseListApiFieldInspection>>;
  public getAvailableForCompanyByMap(
    map: GetAvailableForCompany.PartialParamMap,
    observe: any = 'body',
    reportProgress: boolean = false): Observable<any> {
    return this.getAvailableForCompany(
      map.companyId,
      map.onlyRecommended,
      map.language,
      observe,
      reportProgress
    );
  }


    /**
     * List available field inspections for a company
     * Returns field inspections that are not yet linked to a packing plant delivery
     * @param companyId Company ID
     * @param onlyRecommended Only return inspections where purchase is recommended
     * @param language 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAvailableForCompany(companyId: number, onlyRecommended?: boolean, language?: 'EN' | 'DE' | 'RW' | 'ES', observe?: 'body', reportProgress?: boolean, additionalHeaders?: Array<Array<string>>): Observable<ApiResponseListApiFieldInspection>;
    public getAvailableForCompany(companyId: number, onlyRecommended?: boolean, language?: 'EN' | 'DE' | 'RW' | 'ES', observe?: 'response', reportProgress?: boolean, additionalHeaders?: Array<Array<string>>): Observable<HttpResponse<ApiResponseListApiFieldInspection>>;
    public getAvailableForCompany(companyId: number, onlyRecommended?: boolean, language?: 'EN' | 'DE' | 'RW' | 'ES', observe?: 'events', reportProgress?: boolean, additionalHeaders?: Array<Array<string>>): Observable<HttpEvent<ApiResponseListApiFieldInspection>>;
    public getAvailableForCompany(companyId: number, onlyRecommended?: boolean, language?: 'EN' | 'DE' | 'RW' | 'ES', observe: any = 'body', reportProgress: boolean = false, additionalHeaders?: Array<Array<string>>): Observable<any> {
        if (companyId === null || companyId === undefined) {
            throw new Error('Required parameter companyId was null or undefined when calling getAvailableForCompany.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (onlyRecommended !== undefined && onlyRecommended !== null) {
            queryParameters = queryParameters.set('onlyRecommended', <any>onlyRecommended);
        }

        let headers = this.defaultHeaders;
        if (language !== undefined && language !== null) {
            headers = headers.set('language', String(language));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

            if (additionalHeaders) {
                for(let pair of additionalHeaders) {
                    headers = headers.set(pair[0], pair[1]);
                }
            }

        const handle = this.httpClient.get<ApiResponseListApiFieldInspection>(`${this.configuration.basePath}/api/chain/field-inspection/available/company/${encodeURIComponent(String(companyId))}`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
        if(typeof this.configuration.errorHandler === 'function') {
          return handle.pipe(catchError(err => this.configuration.errorHandler(err, 'getAvailableForCompany')));
        }
        return handle;
    }


  /**
   * Get field inspection by ID by map.
   * 
   * @param map parameters map to set partial amount of parameters easily
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getByIdByMap(
    map: GetById.PartialParamMap,
    observe?: 'body',
    reportProgress?: boolean): Observable<ApiResponseApiFieldInspection>;
  public getByIdByMap(
    map: GetById.PartialParamMap,
    observe?: 'response',
    reportProgress?: boolean): Observable<HttpResponse<ApiResponseApiFieldInspection>>;
  public getByIdByMap(
    map: GetById.PartialParamMap,
    observe?: 'events',
    reportProgress?: boolean): Observable<HttpEvent<ApiResponseApiFieldInspection>>;
  public getByIdByMap(
    map: GetById.PartialParamMap,
    observe: any = 'body',
    reportProgress: boolean = false): Observable<any> {
    return this.getById(
      map.id,
      observe,
      reportProgress
    );
  }


    /**
     * Get field inspection by ID
     * 
     * @param id Field inspection ID
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getById(id: number, observe?: 'body', reportProgress?: boolean, additionalHeaders?: Array<Array<string>>): Observable<ApiResponseApiFieldInspection>;
    public getById(id: number, observe?: 'response', reportProgress?: boolean, additionalHeaders?: Array<Array<string>>): Observable<HttpResponse<ApiResponseApiFieldInspection>>;
    public getById(id: number, observe?: 'events', reportProgress?: boolean, additionalHeaders?: Array<Array<string>>): Observable<HttpEvent<ApiResponseApiFieldInspection>>;
    public getById(id: number, observe: any = 'body', reportProgress: boolean = false, additionalHeaders?: Array<Array<string>>): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling getById.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

            if (additionalHeaders) {
                for(let pair of additionalHeaders) {
                    headers = headers.set(pair[0], pair[1]);
                }
            }

        const handle = this.httpClient.get<ApiResponseApiFieldInspection>(`${this.configuration.basePath}/api/chain/field-inspection/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
        if(typeof this.configuration.errorHandler === 'function') {
          return handle.pipe(catchError(err => this.configuration.errorHandler(err, 'getById')));
        }
        return handle;
    }


  /**
   * Mark field inspection as used by map.
   * Links a field inspection to a destination stock order at the packing plant
   * @param map parameters map to set partial amount of parameters easily
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public markInspectionUsedByMap(
    map: MarkInspectionUsed.PartialParamMap,
    observe?: 'body',
    reportProgress?: boolean): Observable<ApiDefaultResponse>;
  public markInspectionUsedByMap(
    map: MarkInspectionUsed.PartialParamMap,
    observe?: 'response',
    reportProgress?: boolean): Observable<HttpResponse<ApiDefaultResponse>>;
  public markInspectionUsedByMap(
    map: MarkInspectionUsed.PartialParamMap,
    observe?: 'events',
    reportProgress?: boolean): Observable<HttpEvent<ApiDefaultResponse>>;
  public markInspectionUsedByMap(
    map: MarkInspectionUsed.PartialParamMap,
    observe: any = 'body',
    reportProgress: boolean = false): Observable<any> {
    return this.markInspectionUsed(
      map.id,
      map.destinationStockOrderId,
      observe,
      reportProgress
    );
  }


    /**
     * Mark field inspection as used
     * Links a field inspection to a destination stock order at the packing plant
     * @param id Field inspection ID
     * @param destinationStockOrderId Destination StockOrder ID at packing plant
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public markInspectionUsed(id: number, destinationStockOrderId: number, observe?: 'body', reportProgress?: boolean, additionalHeaders?: Array<Array<string>>): Observable<ApiDefaultResponse>;
    public markInspectionUsed(id: number, destinationStockOrderId: number, observe?: 'response', reportProgress?: boolean, additionalHeaders?: Array<Array<string>>): Observable<HttpResponse<ApiDefaultResponse>>;
    public markInspectionUsed(id: number, destinationStockOrderId: number, observe?: 'events', reportProgress?: boolean, additionalHeaders?: Array<Array<string>>): Observable<HttpEvent<ApiDefaultResponse>>;
    public markInspectionUsed(id: number, destinationStockOrderId: number, observe: any = 'body', reportProgress: boolean = false, additionalHeaders?: Array<Array<string>>): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling markInspectionUsed.');
        }
        if (destinationStockOrderId === null || destinationStockOrderId === undefined) {
            throw new Error('Required parameter destinationStockOrderId was null or undefined when calling markInspectionUsed.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (destinationStockOrderId !== undefined && destinationStockOrderId !== null) {
            queryParameters = queryParameters.set('destinationStockOrderId', <any>destinationStockOrderId);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

            if (additionalHeaders) {
                for(let pair of additionalHeaders) {
                    headers = headers.set(pair[0], pair[1]);
                }
            }

        const handle = this.httpClient.post<ApiDefaultResponse>(`${this.configuration.basePath}/api/chain/field-inspection/${encodeURIComponent(String(id))}/mark-used`,
            null,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
        if(typeof this.configuration.errorHandler === 'function') {
          return handle.pipe(catchError(err => this.configuration.errorHandler(err, 'markInspectionUsed')));
        }
        return handle;
    }

}
