/*
 * Copyright(c) 2009 - 2019 Abelium d.o.o.
 * Kajuhova 90, 1000 Ljubljana, Slovenia
 * All rights reserved
 * Copyright(c) 1995 - 2018 T-Systems Multimedia Solutions GmbH
 * Riesaer Str. 5, 01129 Dresden
 * All rights reserved.
 *
 * INATrace Services API
 * INATrace Services API OpenAPI documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the openapi-typescript-angular-generator.
 * https://github.com/alenabelium/openapi-typescript-angular-generator
 * Do not edit the class manually.
 */

/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { ValidatorFn, Validators } from '@angular/forms';

import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';
import { catchError }                                        from 'rxjs/operators';

import { ApiDefaultResponse } from '../model/apiDefaultResponse';
import { ApiPaginatedResponseApiShrimpPresentationType } from '../model/apiPaginatedResponseApiShrimpPresentationType';
import { ApiResponseApiBaseEntity } from '../model/apiResponseApiBaseEntity';
import { ApiResponseApiShrimpPresentationType } from '../model/apiResponseApiShrimpPresentationType';
import { ApiResponseListApiShrimpPresentationType } from '../model/apiResponseListApiShrimpPresentationType';
import { ApiShrimpPresentationType } from '../model/apiShrimpPresentationType';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';

/**
 * Namespace for createOrUpdateShrimpPresentationType.
 */
export namespace CreateOrUpdateShrimpPresentationType {
    /**
     * Parameter map for createOrUpdateShrimpPresentationType.
     */
    export interface PartialParamMap {
      ApiShrimpPresentationType: ApiShrimpPresentationType;
    }

    /**
     * Enumeration of all parameters for createOrUpdateShrimpPresentationType.
     */
    export enum Parameters {
      ApiShrimpPresentationType = 'ApiShrimpPresentationType'
    }

    /**
     * A map of tuples with error name and `ValidatorFn` for each parameter of createOrUpdateShrimpPresentationType
     * that does not have an own model.
     */
    export const ParamValidators: {[K in keyof CreateOrUpdateShrimpPresentationType.PartialParamMap]?: [string, ValidatorFn][]} = {
    };
}

/**
 * Namespace for deleteShrimpPresentationType.
 */
export namespace DeleteShrimpPresentationType {
    /**
     * Parameter map for deleteShrimpPresentationType.
     */
    export interface PartialParamMap {
      /**
       * Shrimp presentation type ID
       */
      id: number;
    }

    /**
     * Enumeration of all parameters for deleteShrimpPresentationType.
     */
    export enum Parameters {
      /**
       * Shrimp presentation type ID
       */
      id = 'id'
    }

    /**
     * A map of tuples with error name and `ValidatorFn` for each parameter of deleteShrimpPresentationType
     * that does not have an own model.
     */
    export const ParamValidators: {[K in keyof DeleteShrimpPresentationType.PartialParamMap]?: [string, ValidatorFn][]} = {
      id: [
              ['required', Validators.required],
      ],
    };
}

/**
 * Namespace for getActiveShrimpPresentationTypes.
 */
export namespace GetActiveShrimpPresentationTypes {
    /**
     * Parameter map for getActiveShrimpPresentationTypes.
     */
    export interface PartialParamMap {
      language?: 'EN' | 'DE' | 'RW' | 'ES';
    }

    /**
     * Enumeration of all parameters for getActiveShrimpPresentationTypes.
     */
    export enum Parameters {
      language = 'language'
    }

    /**
     * A map of tuples with error name and `ValidatorFn` for each parameter of getActiveShrimpPresentationTypes
     * that does not have an own model.
     */
    export const ParamValidators: {[K in keyof GetActiveShrimpPresentationTypes.PartialParamMap]?: [string, ValidatorFn][]} = {
      language: [
      ],
    };
}

/**
 * Namespace for getShrimpPresentationType.
 */
export namespace GetShrimpPresentationType {
    /**
     * Parameter map for getShrimpPresentationType.
     */
    export interface PartialParamMap {
      /**
       * Shrimp presentation type ID
       */
      id: number;
      language?: 'EN' | 'DE' | 'RW' | 'ES';
    }

    /**
     * Enumeration of all parameters for getShrimpPresentationType.
     */
    export enum Parameters {
      /**
       * Shrimp presentation type ID
       */
      id = 'id',
      language = 'language'
    }

    /**
     * A map of tuples with error name and `ValidatorFn` for each parameter of getShrimpPresentationType
     * that does not have an own model.
     */
    export const ParamValidators: {[K in keyof GetShrimpPresentationType.PartialParamMap]?: [string, ValidatorFn][]} = {
      id: [
              ['required', Validators.required],
      ],
      language: [
      ],
    };
}

/**
 * Namespace for getShrimpPresentationTypeList.
 */
export namespace GetShrimpPresentationTypeList {
    /**
     * Parameter map for getShrimpPresentationTypeList.
     */
    export interface PartialParamMap {
      /**
       * Only count, only fetch, or return both values (if null)
       */
      requestType?: 'COUNT' | 'FETCH';
      /**
       * Number of records to return. Min: 1, default: 100
       */
      limit?: number;
      /**
       * Number of records to skip before returning. Default: 0, min: 0
       */
      offset?: number;
      /**
       * Column name to be sorted by, varies for each endpoint, default is id
       */
      sortBy?: string;
      /**
       * Direction of sorting (ASC or DESC). Default DESC.
       */
      sort?: 'ASC' | 'DESC';
      language?: 'EN' | 'DE' | 'RW' | 'ES';
    }

    /**
     * Enumeration of all parameters for getShrimpPresentationTypeList.
     */
    export enum Parameters {
      /**
       * Only count, only fetch, or return both values (if null)
       */
      requestType = 'requestType',
      /**
       * Number of records to return. Min: 1, default: 100
       */
      limit = 'limit',
      /**
       * Number of records to skip before returning. Default: 0, min: 0
       */
      offset = 'offset',
      /**
       * Column name to be sorted by, varies for each endpoint, default is id
       */
      sortBy = 'sortBy',
      /**
       * Direction of sorting (ASC or DESC). Default DESC.
       */
      sort = 'sort',
      language = 'language'
    }

    /**
     * A map of tuples with error name and `ValidatorFn` for each parameter of getShrimpPresentationTypeList
     * that does not have an own model.
     */
    export const ParamValidators: {[K in keyof GetShrimpPresentationTypeList.PartialParamMap]?: [string, ValidatorFn][]} = {
      requestType: [
      ],
      limit: [
              ['min', Validators.min(1)],
      ],
      offset: [
              ['min', Validators.min(0)],
      ],
      sortBy: [
      ],
      sort: [
      ],
      language: [
      ],
    };
}

/**
 * Namespace for getShrimpPresentationTypesByCategory.
 */
export namespace GetShrimpPresentationTypesByCategory {
    /**
     * Parameter map for getShrimpPresentationTypesByCategory.
     */
    export interface PartialParamMap {
      /**
       * Category: SHELL_ON, BROKEN, or OTHER
       */
      category: 'SHELL_ON' | 'BROKEN' | 'OTHER';
      language?: 'EN' | 'DE' | 'RW' | 'ES';
    }

    /**
     * Enumeration of all parameters for getShrimpPresentationTypesByCategory.
     */
    export enum Parameters {
      /**
       * Category: SHELL_ON, BROKEN, or OTHER
       */
      category = 'category',
      language = 'language'
    }

    /**
     * A map of tuples with error name and `ValidatorFn` for each parameter of getShrimpPresentationTypesByCategory
     * that does not have an own model.
     */
    export const ParamValidators: {[K in keyof GetShrimpPresentationTypesByCategory.PartialParamMap]?: [string, ValidatorFn][]} = {
      category: [
              ['required', Validators.required],
      ],
      language: [
      ],
    };
}



@Injectable({
  providedIn: 'root'
})
export class ShrimpPresentationTypeControllerService {

    protected basePath = 'http://192.168.100.187:8080';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {

        if (configuration) {
            this.configuration = configuration;
            this.configuration.basePath = configuration.basePath != null ? configuration.basePath : (basePath != null ? basePath : this.basePath);
        } else {
            this.configuration.basePath = basePath != null ? basePath : this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }



  /**
   * Create or update shrimp presentation type. If ID is provided, the entity with the provided ID is updated. by map.
   * 
   * @param map parameters map to set partial amount of parameters easily
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public createOrUpdateShrimpPresentationTypeByMap(
    map: CreateOrUpdateShrimpPresentationType.PartialParamMap,
    observe?: 'body',
    reportProgress?: boolean): Observable<ApiResponseApiBaseEntity>;
  public createOrUpdateShrimpPresentationTypeByMap(
    map: CreateOrUpdateShrimpPresentationType.PartialParamMap,
    observe?: 'response',
    reportProgress?: boolean): Observable<HttpResponse<ApiResponseApiBaseEntity>>;
  public createOrUpdateShrimpPresentationTypeByMap(
    map: CreateOrUpdateShrimpPresentationType.PartialParamMap,
    observe?: 'events',
    reportProgress?: boolean): Observable<HttpEvent<ApiResponseApiBaseEntity>>;
  public createOrUpdateShrimpPresentationTypeByMap(
    map: CreateOrUpdateShrimpPresentationType.PartialParamMap,
    observe: any = 'body',
    reportProgress: boolean = false): Observable<any> {
    return this.createOrUpdateShrimpPresentationType(
      map.ApiShrimpPresentationType,
      observe,
      reportProgress
    );
  }


    /**
     * Create or update shrimp presentation type. If ID is provided, the entity with the provided ID is updated.
     * 
     * @param ApiShrimpPresentationType 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createOrUpdateShrimpPresentationType(ApiShrimpPresentationType: ApiShrimpPresentationType, observe?: 'body', reportProgress?: boolean, additionalHeaders?: Array<Array<string>>): Observable<ApiResponseApiBaseEntity>;
    public createOrUpdateShrimpPresentationType(ApiShrimpPresentationType: ApiShrimpPresentationType, observe?: 'response', reportProgress?: boolean, additionalHeaders?: Array<Array<string>>): Observable<HttpResponse<ApiResponseApiBaseEntity>>;
    public createOrUpdateShrimpPresentationType(ApiShrimpPresentationType: ApiShrimpPresentationType, observe?: 'events', reportProgress?: boolean, additionalHeaders?: Array<Array<string>>): Observable<HttpEvent<ApiResponseApiBaseEntity>>;
    public createOrUpdateShrimpPresentationType(ApiShrimpPresentationType: ApiShrimpPresentationType, observe: any = 'body', reportProgress: boolean = false, additionalHeaders?: Array<Array<string>>): Observable<any> {
        if (ApiShrimpPresentationType === null || ApiShrimpPresentationType === undefined) {
            throw new Error('Required parameter ApiShrimpPresentationType was null or undefined when calling createOrUpdateShrimpPresentationType.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

            if (additionalHeaders) {
                for(let pair of additionalHeaders) {
                    headers = headers.set(pair[0], pair[1]);
                }
            }

        const handle = this.httpClient.put<ApiResponseApiBaseEntity>(`${this.configuration.basePath}/api/chain/shrimp-presentation-type`,
            ApiShrimpPresentationType,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
        if(typeof this.configuration.errorHandler === 'function') {
          return handle.pipe(catchError(err => this.configuration.errorHandler(err, 'createOrUpdateShrimpPresentationType')));
        }
        return handle;
    }


  /**
   * Deletes a shrimp presentation type with the provided ID. by map.
   * 
   * @param map parameters map to set partial amount of parameters easily
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public deleteShrimpPresentationTypeByMap(
    map: DeleteShrimpPresentationType.PartialParamMap,
    observe?: 'body',
    reportProgress?: boolean): Observable<ApiDefaultResponse>;
  public deleteShrimpPresentationTypeByMap(
    map: DeleteShrimpPresentationType.PartialParamMap,
    observe?: 'response',
    reportProgress?: boolean): Observable<HttpResponse<ApiDefaultResponse>>;
  public deleteShrimpPresentationTypeByMap(
    map: DeleteShrimpPresentationType.PartialParamMap,
    observe?: 'events',
    reportProgress?: boolean): Observable<HttpEvent<ApiDefaultResponse>>;
  public deleteShrimpPresentationTypeByMap(
    map: DeleteShrimpPresentationType.PartialParamMap,
    observe: any = 'body',
    reportProgress: boolean = false): Observable<any> {
    return this.deleteShrimpPresentationType(
      map.id,
      observe,
      reportProgress
    );
  }


    /**
     * Deletes a shrimp presentation type with the provided ID.
     * 
     * @param id Shrimp presentation type ID
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteShrimpPresentationType(id: number, observe?: 'body', reportProgress?: boolean, additionalHeaders?: Array<Array<string>>): Observable<ApiDefaultResponse>;
    public deleteShrimpPresentationType(id: number, observe?: 'response', reportProgress?: boolean, additionalHeaders?: Array<Array<string>>): Observable<HttpResponse<ApiDefaultResponse>>;
    public deleteShrimpPresentationType(id: number, observe?: 'events', reportProgress?: boolean, additionalHeaders?: Array<Array<string>>): Observable<HttpEvent<ApiDefaultResponse>>;
    public deleteShrimpPresentationType(id: number, observe: any = 'body', reportProgress: boolean = false, additionalHeaders?: Array<Array<string>>): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling deleteShrimpPresentationType.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

            if (additionalHeaders) {
                for(let pair of additionalHeaders) {
                    headers = headers.set(pair[0], pair[1]);
                }
            }

        const handle = this.httpClient.delete<ApiDefaultResponse>(`${this.configuration.basePath}/api/chain/shrimp-presentation-type/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
        if(typeof this.configuration.errorHandler === 'function') {
          return handle.pipe(catchError(err => this.configuration.errorHandler(err, 'deleteShrimpPresentationType')));
        }
        return handle;
    }


  /**
   * Get a list of active shrimp presentation types. by map.
   * 
   * @param map parameters map to set partial amount of parameters easily
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getActiveShrimpPresentationTypesByMap(
    map: GetActiveShrimpPresentationTypes.PartialParamMap,
    observe?: 'body',
    reportProgress?: boolean): Observable<ApiResponseListApiShrimpPresentationType>;
  public getActiveShrimpPresentationTypesByMap(
    map: GetActiveShrimpPresentationTypes.PartialParamMap,
    observe?: 'response',
    reportProgress?: boolean): Observable<HttpResponse<ApiResponseListApiShrimpPresentationType>>;
  public getActiveShrimpPresentationTypesByMap(
    map: GetActiveShrimpPresentationTypes.PartialParamMap,
    observe?: 'events',
    reportProgress?: boolean): Observable<HttpEvent<ApiResponseListApiShrimpPresentationType>>;
  public getActiveShrimpPresentationTypesByMap(
    map: GetActiveShrimpPresentationTypes.PartialParamMap,
    observe: any = 'body',
    reportProgress: boolean = false): Observable<any> {
    return this.getActiveShrimpPresentationTypes(
      map.language,
      observe,
      reportProgress
    );
  }


    /**
     * Get a list of active shrimp presentation types.
     * 
     * @param language 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getActiveShrimpPresentationTypes(language?: 'EN' | 'DE' | 'RW' | 'ES', observe?: 'body', reportProgress?: boolean, additionalHeaders?: Array<Array<string>>): Observable<ApiResponseListApiShrimpPresentationType>;
    public getActiveShrimpPresentationTypes(language?: 'EN' | 'DE' | 'RW' | 'ES', observe?: 'response', reportProgress?: boolean, additionalHeaders?: Array<Array<string>>): Observable<HttpResponse<ApiResponseListApiShrimpPresentationType>>;
    public getActiveShrimpPresentationTypes(language?: 'EN' | 'DE' | 'RW' | 'ES', observe?: 'events', reportProgress?: boolean, additionalHeaders?: Array<Array<string>>): Observable<HttpEvent<ApiResponseListApiShrimpPresentationType>>;
    public getActiveShrimpPresentationTypes(language?: 'EN' | 'DE' | 'RW' | 'ES', observe: any = 'body', reportProgress: boolean = false, additionalHeaders?: Array<Array<string>>): Observable<any> {

        let headers = this.defaultHeaders;
        if (language !== undefined && language !== null) {
            headers = headers.set('language', String(language));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

            if (additionalHeaders) {
                for(let pair of additionalHeaders) {
                    headers = headers.set(pair[0], pair[1]);
                }
            }

        const handle = this.httpClient.get<ApiResponseListApiShrimpPresentationType>(`${this.configuration.basePath}/api/chain/shrimp-presentation-type/list/active`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
        if(typeof this.configuration.errorHandler === 'function') {
          return handle.pipe(catchError(err => this.configuration.errorHandler(err, 'getActiveShrimpPresentationTypes')));
        }
        return handle;
    }


  /**
   * Get a single shrimp presentation type with the provided ID. by map.
   * 
   * @param map parameters map to set partial amount of parameters easily
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getShrimpPresentationTypeByMap(
    map: GetShrimpPresentationType.PartialParamMap,
    observe?: 'body',
    reportProgress?: boolean): Observable<ApiResponseApiShrimpPresentationType>;
  public getShrimpPresentationTypeByMap(
    map: GetShrimpPresentationType.PartialParamMap,
    observe?: 'response',
    reportProgress?: boolean): Observable<HttpResponse<ApiResponseApiShrimpPresentationType>>;
  public getShrimpPresentationTypeByMap(
    map: GetShrimpPresentationType.PartialParamMap,
    observe?: 'events',
    reportProgress?: boolean): Observable<HttpEvent<ApiResponseApiShrimpPresentationType>>;
  public getShrimpPresentationTypeByMap(
    map: GetShrimpPresentationType.PartialParamMap,
    observe: any = 'body',
    reportProgress: boolean = false): Observable<any> {
    return this.getShrimpPresentationType(
      map.id,
      map.language,
      observe,
      reportProgress
    );
  }


    /**
     * Get a single shrimp presentation type with the provided ID.
     * 
     * @param id Shrimp presentation type ID
     * @param language 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getShrimpPresentationType(id: number, language?: 'EN' | 'DE' | 'RW' | 'ES', observe?: 'body', reportProgress?: boolean, additionalHeaders?: Array<Array<string>>): Observable<ApiResponseApiShrimpPresentationType>;
    public getShrimpPresentationType(id: number, language?: 'EN' | 'DE' | 'RW' | 'ES', observe?: 'response', reportProgress?: boolean, additionalHeaders?: Array<Array<string>>): Observable<HttpResponse<ApiResponseApiShrimpPresentationType>>;
    public getShrimpPresentationType(id: number, language?: 'EN' | 'DE' | 'RW' | 'ES', observe?: 'events', reportProgress?: boolean, additionalHeaders?: Array<Array<string>>): Observable<HttpEvent<ApiResponseApiShrimpPresentationType>>;
    public getShrimpPresentationType(id: number, language?: 'EN' | 'DE' | 'RW' | 'ES', observe: any = 'body', reportProgress: boolean = false, additionalHeaders?: Array<Array<string>>): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling getShrimpPresentationType.');
        }

        let headers = this.defaultHeaders;
        if (language !== undefined && language !== null) {
            headers = headers.set('language', String(language));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

            if (additionalHeaders) {
                for(let pair of additionalHeaders) {
                    headers = headers.set(pair[0], pair[1]);
                }
            }

        const handle = this.httpClient.get<ApiResponseApiShrimpPresentationType>(`${this.configuration.basePath}/api/chain/shrimp-presentation-type/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
        if(typeof this.configuration.errorHandler === 'function') {
          return handle.pipe(catchError(err => this.configuration.errorHandler(err, 'getShrimpPresentationType')));
        }
        return handle;
    }


  /**
   * Get a paginated list of shrimp presentation types. by map.
   * 
   * @param map parameters map to set partial amount of parameters easily
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getShrimpPresentationTypeListByMap(
    map: GetShrimpPresentationTypeList.PartialParamMap,
    observe?: 'body',
    reportProgress?: boolean): Observable<ApiPaginatedResponseApiShrimpPresentationType>;
  public getShrimpPresentationTypeListByMap(
    map: GetShrimpPresentationTypeList.PartialParamMap,
    observe?: 'response',
    reportProgress?: boolean): Observable<HttpResponse<ApiPaginatedResponseApiShrimpPresentationType>>;
  public getShrimpPresentationTypeListByMap(
    map: GetShrimpPresentationTypeList.PartialParamMap,
    observe?: 'events',
    reportProgress?: boolean): Observable<HttpEvent<ApiPaginatedResponseApiShrimpPresentationType>>;
  public getShrimpPresentationTypeListByMap(
    map: GetShrimpPresentationTypeList.PartialParamMap,
    observe: any = 'body',
    reportProgress: boolean = false): Observable<any> {
    return this.getShrimpPresentationTypeList(
      map.requestType,
      map.limit,
      map.offset,
      map.sortBy,
      map.sort,
      map.language,
      observe,
      reportProgress
    );
  }


    /**
     * Get a paginated list of shrimp presentation types.
     * 
     * @param requestType Only count, only fetch, or return both values (if null)
     * @param limit Number of records to return. Min: 1, default: 100
     * @param offset Number of records to skip before returning. Default: 0, min: 0
     * @param sortBy Column name to be sorted by, varies for each endpoint, default is id
     * @param sort Direction of sorting (ASC or DESC). Default DESC.
     * @param language 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getShrimpPresentationTypeList(requestType?: 'COUNT' | 'FETCH', limit?: number, offset?: number, sortBy?: string, sort?: 'ASC' | 'DESC', language?: 'EN' | 'DE' | 'RW' | 'ES', observe?: 'body', reportProgress?: boolean, additionalHeaders?: Array<Array<string>>): Observable<ApiPaginatedResponseApiShrimpPresentationType>;
    public getShrimpPresentationTypeList(requestType?: 'COUNT' | 'FETCH', limit?: number, offset?: number, sortBy?: string, sort?: 'ASC' | 'DESC', language?: 'EN' | 'DE' | 'RW' | 'ES', observe?: 'response', reportProgress?: boolean, additionalHeaders?: Array<Array<string>>): Observable<HttpResponse<ApiPaginatedResponseApiShrimpPresentationType>>;
    public getShrimpPresentationTypeList(requestType?: 'COUNT' | 'FETCH', limit?: number, offset?: number, sortBy?: string, sort?: 'ASC' | 'DESC', language?: 'EN' | 'DE' | 'RW' | 'ES', observe?: 'events', reportProgress?: boolean, additionalHeaders?: Array<Array<string>>): Observable<HttpEvent<ApiPaginatedResponseApiShrimpPresentationType>>;
    public getShrimpPresentationTypeList(requestType?: 'COUNT' | 'FETCH', limit?: number, offset?: number, sortBy?: string, sort?: 'ASC' | 'DESC', language?: 'EN' | 'DE' | 'RW' | 'ES', observe: any = 'body', reportProgress: boolean = false, additionalHeaders?: Array<Array<string>>): Observable<any> {

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (requestType !== undefined && requestType !== null) {
            queryParameters = queryParameters.set('requestType', <any>requestType);
        }
        if (limit !== undefined && limit !== null) {
            queryParameters = queryParameters.set('limit', <any>limit);
        }
        if (offset !== undefined && offset !== null) {
            queryParameters = queryParameters.set('offset', <any>offset);
        }
        if (sortBy !== undefined && sortBy !== null) {
            queryParameters = queryParameters.set('sortBy', <any>sortBy);
        }
        if (sort !== undefined && sort !== null) {
            queryParameters = queryParameters.set('sort', <any>sort);
        }

        let headers = this.defaultHeaders;
        if (language !== undefined && language !== null) {
            headers = headers.set('language', String(language));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

            if (additionalHeaders) {
                for(let pair of additionalHeaders) {
                    headers = headers.set(pair[0], pair[1]);
                }
            }

        const handle = this.httpClient.get<ApiPaginatedResponseApiShrimpPresentationType>(`${this.configuration.basePath}/api/chain/shrimp-presentation-type/list`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
        if(typeof this.configuration.errorHandler === 'function') {
          return handle.pipe(catchError(err => this.configuration.errorHandler(err, 'getShrimpPresentationTypeList')));
        }
        return handle;
    }


  /**
   * Get a list of active shrimp presentation types by category (SHELL_ON, BROKEN, OTHER). by map.
   * 
   * @param map parameters map to set partial amount of parameters easily
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getShrimpPresentationTypesByCategoryByMap(
    map: GetShrimpPresentationTypesByCategory.PartialParamMap,
    observe?: 'body',
    reportProgress?: boolean): Observable<ApiResponseListApiShrimpPresentationType>;
  public getShrimpPresentationTypesByCategoryByMap(
    map: GetShrimpPresentationTypesByCategory.PartialParamMap,
    observe?: 'response',
    reportProgress?: boolean): Observable<HttpResponse<ApiResponseListApiShrimpPresentationType>>;
  public getShrimpPresentationTypesByCategoryByMap(
    map: GetShrimpPresentationTypesByCategory.PartialParamMap,
    observe?: 'events',
    reportProgress?: boolean): Observable<HttpEvent<ApiResponseListApiShrimpPresentationType>>;
  public getShrimpPresentationTypesByCategoryByMap(
    map: GetShrimpPresentationTypesByCategory.PartialParamMap,
    observe: any = 'body',
    reportProgress: boolean = false): Observable<any> {
    return this.getShrimpPresentationTypesByCategory(
      map.category,
      map.language,
      observe,
      reportProgress
    );
  }


    /**
     * Get a list of active shrimp presentation types by category (SHELL_ON, BROKEN, OTHER).
     * 
     * @param category Category: SHELL_ON, BROKEN, or OTHER
     * @param language 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getShrimpPresentationTypesByCategory(category: 'SHELL_ON' | 'BROKEN' | 'OTHER', language?: 'EN' | 'DE' | 'RW' | 'ES', observe?: 'body', reportProgress?: boolean, additionalHeaders?: Array<Array<string>>): Observable<ApiResponseListApiShrimpPresentationType>;
    public getShrimpPresentationTypesByCategory(category: 'SHELL_ON' | 'BROKEN' | 'OTHER', language?: 'EN' | 'DE' | 'RW' | 'ES', observe?: 'response', reportProgress?: boolean, additionalHeaders?: Array<Array<string>>): Observable<HttpResponse<ApiResponseListApiShrimpPresentationType>>;
    public getShrimpPresentationTypesByCategory(category: 'SHELL_ON' | 'BROKEN' | 'OTHER', language?: 'EN' | 'DE' | 'RW' | 'ES', observe?: 'events', reportProgress?: boolean, additionalHeaders?: Array<Array<string>>): Observable<HttpEvent<ApiResponseListApiShrimpPresentationType>>;
    public getShrimpPresentationTypesByCategory(category: 'SHELL_ON' | 'BROKEN' | 'OTHER', language?: 'EN' | 'DE' | 'RW' | 'ES', observe: any = 'body', reportProgress: boolean = false, additionalHeaders?: Array<Array<string>>): Observable<any> {
        if (category === null || category === undefined) {
            throw new Error('Required parameter category was null or undefined when calling getShrimpPresentationTypesByCategory.');
        }

        let headers = this.defaultHeaders;
        if (language !== undefined && language !== null) {
            headers = headers.set('language', String(language));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

            if (additionalHeaders) {
                for(let pair of additionalHeaders) {
                    headers = headers.set(pair[0], pair[1]);
                }
            }

        const handle = this.httpClient.get<ApiResponseListApiShrimpPresentationType>(`${this.configuration.basePath}/api/chain/shrimp-presentation-type/list/category/${encodeURIComponent(String(category))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
        if(typeof this.configuration.errorHandler === 'function') {
          return handle.pipe(catchError(err => this.configuration.errorHandler(err, 'getShrimpPresentationTypesByCategory')));
        }
        return handle;
    }

}
